apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-prueba-tecnica
resources:
  - namespace.yaml
  - mysql-secret.yaml
  - mysql-configmap.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - backend-secret.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
