# Credenciales MySQL - Sustituir los valores en base64
# echo -n 'tu_password' | base64
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: user-management
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root123"
  MYSQL_DATABASE: "users_db"
  MYSQL_USER: "app"
  MYSQL_PASSWORD: "app123"
